name: "Pull Request: Get metadata"

on:
  workflow_call:
    outputs:
      isRenovatePR:
        description: "Is the PR coming from Renovate?"
        value: ${{ jobs.pr-metadata.outputs.isRenovatePR }}
      isFork:
        description: "Is the PR coming from a forked repo?"
        value: ${{ jobs.pr-metadata.outputs.isFork }}
      addedOrModifiedFilesDetected:
        description: "Does the PR contain any changes?"
        value: ${{ jobs.pr-changes.outputs.addedOrModifiedFilesDetected }}
      addedOrModifiedFiles:
        description: "A list of the files changed in this PR"
        value: ${{ jobs.pr-changes.outputs.addedOrModifiedFiles }}
      addedOrModifiedCharts:
        description: "A list of the charts changed in this PR"
        value: ${{ jobs.pr-changes.outputs.addedOrModifiedCharts }}
      chartsToLint:
        value: ${{ jobs.pr-changes.outputs.chartsToLint }}
      chartsToInstall:
        value: ${{ jobs.pr-changes.outputs.chartsToInstall }}
      commonLibraryUpdated:
        value: ${{ jobs.pr-changes.outputs.commonLibraryUpdated }}

jobs:
  pr-metadata:
    name: Collect PR metadata
    runs-on: ubuntu-22.04
    outputs:
      isRenovatePR: ${{ startsWith(steps.branch-name.outputs.current_branch, 'renovate/') }}
      isFork: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@2e5354c6733793113f416314375826df030ada23 # v6.5

      - name: Save PR data to file
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > pr_number.txt

      - name: Store pr data in artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: pr_metadata
          path: ./pr_number.txt
          retention-days: 5

  pr-changes:
    name: Collect PR changes
    runs-on: ubuntu-22.04
    outputs:
      addedOrModifiedFilesDetected: ${{ steps.changed-files.outputs.allAddedOrModified }}
      addedOrModifiedFiles: ${{ steps.changed-files.outputs.allAddedOrModified_files }}
      addedOrModifiedCharts: ${{ steps.changed-charts.outputs.charts }}
      addedOrModifiedLibraryCharts: ${{ steps.changed-charts.outputs.chartsLibrary }}
      addedOrModifiedApplicationCharts: ${{ steps.changed-charts.outputs.chartsApplication }}
      chartsToLint: ${{ steps.changed-charts.outputs.chartsToLint }}
      chartsToInstall: ${{ steps.changed-charts.outputs.chartsToInstall }}
      commonLibraryUpdated: ${{ contains(fromJSON(steps.changed-charts.outputs.charts), 'library/common') }}
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      - name: Collect changed files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: changed-files
        with:
          list-files: json
          filters: |
            allAddedOrModified:
              - added|modified: '**'

      - name: Collect changed charts
        uses: raypappa/helm-charts-actions/collect-charts@main
        id: changed-charts
